// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obmvykgxepewhykctzzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibXZ5a2d4ZXBld2h5a2N0enprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzkyNTcsImV4cCI6MjA2MDE1NTI1N30.WncABqR5QyOW5QEQfaAHCZACZht56JW45KhVf4fz3CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);